### ISSUE TITLE
WebUI - Watering multiple zones with custom duration is hard to do

### ISSUE THREAD

**Issue by mbdroid** [sprinkler/rainmachine-web-ui#111]
While watering a zone the duration for the stopped zones is set to the default value every 2 seconds (overwriting any value you are writing)

Steps to reproduce:
* Start a zone (eg. zone 2)
* While the zone is watering, there is a refresh happening that updates the duration for the stopped zones to their default values
 * change the duration for another zone (eg. zone 3); in 1-3s, the value will be reset back to the default for that zone
 * trying to queue a zone with a custom duration will result either in starting it with the default value or with the set duration
* having a running zone and a pending one, stopping a pending zone will result in that zone being set a default watering duration of 00:00
 * checking the android app, the zone that was stopped at the previous step appears as being "pending" with duration 00:00

**Comment by nicupavel** [comment]
I'd say impossible :). That's because the entire div is being recreated. This needs to be changed so the elements only updated if necessary. The entire dashboard/zones/programs page will be redesigned so this not be fixed in current design.

**Comment by nicupavel** [comment]
New layout should fix this
