### ISSUE TITLE
Design - SPK1/SPK2 - Minutes and Seconds from the zone page should be on the same line

### ISSUE THREAD

**Issue by alexmireav** [sprinkler/rainmachine-web-ui#13]
It makes sense that we place them on the same line in the format MM : SS 
It doesn't make sense to have seconds on the top line, to the right and the minutes on the bottom row

Also, move the start button to the right lower corner (where the Minutes tab is now) and leave the edit button where it is. It makes sense.

**Comment by alexmireav** [comment]
![design231](https://cloud.githubusercontent.com/assets/11552270/9037602/9c86602a-39f5-11e5-8a64-ae4500d17af1.jpg)

**Comment by nicupavel** [comment]
<img width="1280" alt="screen shot 2015-08-03 at 15 40 27" src="https://cloud.githubusercontent.com/assets/1650801/9037817/ac5523a4-39f7-11e5-9226-c063f1f483a0.png">


Looks fine on Mac and Linux, maybe @lucaiuli could check this out.

**Comment by alexmireav** [comment]
@nicupavel yeah, that exactly what I was going for. Thanks for the reference
