### ISSUE TITLE
Dashboard - Beta - The Zones watering times are placed incorrectly and are not very logical as far as watering time goes

### ISSUE THREAD

**Issue by alexmireav** [sprinkler/rainmachine-web-ui#143]
Please observe the screenshot. We are showing seconds (e.g 600 seconds) instead of minutes when controlling the Zone Watering bar. If it stays static, after the page loads, it shows 5 minutes. This doesn't make sense.

Also, Zone 1 (i'm guessing due to it being Master Valve?) has the watering time indicator way out, in the right side of the page, against a white background.

![sad](https://cloud.githubusercontent.com/assets/11552270/10998920/739b77b2-84a1-11e5-9666-b5620a4d0c10.jpg)

**Comment by nicupavel** [comment]
newlayout branch it's a work in progress, but the screenshot doesn't seem to be from the HEAD of the branch.
