### ISSUE TITLE
WebUI> Programs> Edit/ New program> 'Wheather' text appears instead of 'Weather'

### ISSUE THREAD

**Issue by danieltaivan** [sprinkler/rainmachine-web-ui#168]
STEPS:
1. Open https://my.rainmachine.com
2. Navigate to Programs tab> Edit/ New program
3. Check Weather label

ACTUAL RESULT:
 'Wheather' text appears instead of 'Weather'

**Comment by danieltaivan** [comment]
![wheather](https://cloud.githubusercontent.com/assets/16254241/12048933/cb5468d4-aee9-11e5-868a-bea23496777a.png)

**Comment by alexmireav** [comment]
Issue present on SPK1/2/3
