### ISSUE TITLE
WebUI - System Settings - Measuring units cannot be changed from the WebUI as selecting any unit and pressing Change will not do anything 

### ISSUE THREAD

**Issue by alexmireav** [sprinkler/rainmachine-web-ui#169]
Please note, this issue has been opened before. The explanation there was that the change is remembered in the browser's cache.

Now, I'm pretty sure we should have persistence in between platforms. So, if I make this modification on the WebUI, I should be able to see it on my mobile device.

Steps to repro:
1. Log into WebUI with an account that contains a SPK2/3
2. Go to Settings - System Settings 
3. Change units
4. Use a device (iOS/Android) and see that the change only occurs on the WebUI platform

**Comment by alexmireav** [comment]
Issue is present on SPK1/2/3

**Comment by nicupavel** [comment]
But there isn't a provision variable for units on device, as device always send SI units. There was a locationUnits some time ago but we no longer save this to DB, as it was discussed that clients keep their own settings for this. Can you please check how iOS/Android handles this ?
