### ISSUE TITLE
Functionality/Design - SPK2 - The Snooze field is present beneath the Watering History page 

### ISSUE THREAD

**Issue by alexmireav** [sprinkler/rainmachine-web-ui#17]
The Snooze field should be present in the Watering History page. After pressing Snooze from the Menu (top menu) and returning to the History page, it will vanish.

Repro:
- Connect to a SPK 2 Web UI
- Proceed to Settings
- Scroll down (naturally, the user will be taken to the Watering History page)
- Notice that the Snooze field is present
- Click the Snooze menu from the top menu
- Backtrack to the Watering History page
- Scroll down
- Notice that the Snooze field has vanished

**Comment by nicupavel** [comment]
Not present on next branch
