### ISSUE TITLE
Functionality/Design - SPK1 - Deactivated zones vanish from the Zone View

### ISSUE THREAD

**Issue by alexmireav** [sprinkler/rainmachine-web-ui#18]
I was testing the SPK1 Web UI and it occurred to me that I am not seeing zone 1. I jumped to a SPK2 and saw that Zone 1 is present and can be converted to Master Valve. 

I'm testing on http://10.1.10.96/index.html and I can't find a way to enable/disable the Master Valve - zone 1 is not present.

![temp1](https://cloud.githubusercontent.com/assets/11552270/9055962/12ed0280-3a98-11e5-8783-fbf60a454740.jpg)

**Comment by adrianeavaz** [comment]
The request to /api/4/zone only returns 11 zones. 

![image](https://cloud.githubusercontent.com/assets/7911114/9085084/607a0bfc-3b82-11e5-889d-ed97c5f73628.png)

**Comment by cdumitriu** [comment]
fixed
