### ISSUE TITLE
Request URLs are set with relative paths

### ISSUE THREAD

**Issue by radubaciu** [sprinkler/rainmachine-web-ui#2]
Current URL: /api/4/auth/login
All requests which are forwarded by proxy server must have absolute URLs:
/sprinklerId/api/4/auth/login otherwise proxy server will reject them

**Comment by nicupavel** [comment]
Should we add a local storage key sprinklerid and append it to API url ?

**Comment by bnitulescu-tremend** [comment]
No, it's better if we convert them into relative URLs if possible. This way we have the same code regardless if we go via a server or direct local access.

**Comment by nicupavel** [comment]
https://github.com/sprinkler/rainmachine-web-ui/blob/master/js/rainmachine-api-v4.js

Look at the source  how the requests are made. You can fork and send me a pull request.
