### ISSUE TITLE
SPK1 - WEBUI - Remove the following screens (see content)

### ISSUE THREAD

**Issue by alexmireav** [sprinkler/rainmachine-web-ui#22]
Settings - Location - remove it
Settings - Date & Time (there is a field here with Message/Status code) <- remove it
About - View log - remove it
Settings - Advanced settings - remove the lower part of the page (sensitive stuff here)

**Comment by alexmireav** [comment]
Elements and fuctionality removed.
Verified. Thanks

**Comment by alexmireav** [comment]
Can you please remove the Hourly Restrictions from the Restriction page?

**Comment by adrianeavaz** [comment]
Done.

**Comment by alexmireav** [comment]
Thank you. Verified.

**Comment by alexmireav** [comment]
One more that slipped: The Weather Tab - here we have Rain sensitivity present only on the local UI of the SPK1 (not present in either apps)

@bnitulescu-tremend - should we remove the Weather tab or hide it? -- there's only one element we could feature on this page (Rain Sensitivity control and extra info)
