### ISSUE TITLE
The Remote Access option doesn't send confirmation email

### ISSUE THREAD

**Issue by cosminctinescu** [sprinkler/rainmachine-web-ui#241]
If I set a new email for remote control, the confirmation email is not sent.
Steps to replicate:
1. Log in on my.rainmachine.com
2. Go to the "Settings" window
3. Go to the "System Settings: options
4. Type a new email in the "Remote Access" section
5. Click on Change
The new remote email is added in SPK but the confirmation email is not sent.

**Comment by nicupavel** [comment]
This is known, we don't use the Remote Access API for this since it wasn't yet publicly released.
