### ISSUE TITLE
Wrong sunrise time for NY Location

### ISSUE THREAD

**Issue by cosminctinescu** [sprinkler/rainmachine-web-ui#257]
Wrong sunrise time for the NY Location.

Steps to reproduce:
1. Set the sprinkler's location to Long Island New York
2. Set a new program to start at 0 minute before sunrise

Notice that the sprinkler's sunrise time is not the correct one
![screenshot_6](https://cloud.githubusercontent.com/assets/20169706/18010085/b7adfb16-6bb7-11e6-927a-495ba5769aef.jpg)

**Comment by nicupavel** [comment]
Looks like it's shown considering local timezone instead of device timezone.
What branch are you testing this ?

**Comment by cosminctinescu** [comment]
![screenshot_4](https://cloud.githubusercontent.com/assets/20169706/18059092/f798fb62-6e1f-11e6-94df-31c098eb43c9.jpg)

I don't know the branch version.
