### ISSUE TITLE
Functionality - SPK1 - There is an issue with the POST commands coming from settings

### ISSUE THREAD

**Issue by alexmireav** [sprinkler/rainmachine-web-ui#3]
http://10.1.10.96/index.html -> Settings -> Weather

- Move the slider to other values
- Press default
- Observe that the defaults do not jump back (80 and 50)

- Move the sliders to other values
- Press Save
- Wait a few seconds
- Refresh the connection
- Notice that they have defaulted

**Comment by cdumitriu** [comment]
Updated functionality; POST is not available because the sliders are gone...
