### ISSUE TITLE
SPK2/3 patches merge

### ISSUE THREAD

**Issue by nicupavel** [sprinkler/rainmachine-web-ui#31]
Hi guys,
@sprinkler @lucaiuli @adrianeavaz @bnitulescu-tremend @theotanase

I'm selecting this patches for inclusion in [next/master](https://github.com/sprinkler/rainmachine-web-ui/commits/master) from the [develop](https://github.com/sprinkler/rainmachine-web-ui/commits/develop) branch:

6ba542b746134b69bf9af2198c7afd4b1403ba22
43e7c287d255b3ef1e358cebb602f2bbaff73893
9ceee72549d903fcd9948653b89524f45ced1698
e37cc0ce0e662ce7028486e15bc06448899c7d27
0da5d85188502a612b6a2716a1036e6e92b8b481
85b54703609d7c2fc5ed5352ea2870b1b9bef1c1
0056c5620b122703f7bad0f856bbf64a4a5ff2ce
b9cfbf11bf4b5f6f3f9a7286b215cbd833ec1ee1
ab8b5b20f53aa8a8790febbcfed53bd852dccc19

This will be good too but it will need rewrite: 3b1648a40b33bd8f4f4f7fbd32354b3171afe523

Let me know if I'm overlooking something for SPK2/3.

**Comment by bnitulescu-tremend** [comment]
Hello Nicu,

Theo (@theotanase <https://github.com/theotanase>) is converting right 
now the API calls in the zones screen into asynchronous calls. He hopes 
to finish by the end of the day.

I think it's worth the wait, since the Zones screen is otherwise hard to 
use over the cloud.

Bogdan

**Comment by nicupavel** [comment]
Develop branch has diverged too much and per fix branches are synced not with master but with develop and other fixes for SPK1. This is difficult to integrate.

I will add a common "framework" for async/sync API calls so we can slowly move toward async.

IMO SPK1 fixes should be made like a shim maybe with another .js file that overwrites code from the rest of .js files. This is be easier to manage.
