### ISSUE TITLE
SPK1 - 302 redirect from http://<sprinkler.ip> and https://<sprinkler.ip>  to https://<sprinkler.ip>/ui

### ISSUE THREAD

**Issue by sprinkler** [sprinkler/rainmachine-web-ui#34]
When accessing the SPK1 on the local network, the user will type directly the IP address into the browser.

Please make sure http is redirected to https and the request is redirected to the home page of the ui ( e.g. https://192.168.1.100/ui )

**Comment by mbdroid** [comment]
The following redirects are now performed from lighttpd:
```
http://<sprinkler.ip>/  ---> http://<sprinkler.ip>/ui 
https://<sprinkler.ip>/ ---> https://<sprinkler.ip>/ui 
```
http should be redirected to https from html/javascript
