### ISSUE TITLE
Please add in the Zones page a visual indicator for when the user starts/stops/resumes a zone.

### ISSUE THREAD

**Issue by cdumitriu** [sprinkler/rainmachine-web-ui#44]
Due to a 3 second delay between the START/STOP buttons and the actual spk1 response we recommend a graphic visualizer that indicates the user that they selected something and that action is now pending to be executed.

**Comment by alexmireav** [comment]
Verified

**Comment by cdumitriu** [comment]
Please update the zone START behavior to act in the same way as the android app:
1. When selecting START for a zone place right away a pending message on the zone box and start a non-blocking spinner on the item;
2. Only when the sprinkler registers the POST command start the actual spin wheel for running; 
3. Even if the remaining duration was decremented wait for the spk response to show the zone has started;
