### ISSUE TITLE
WebUI - Remove the Stop all button from Program

### ISSUE THREAD

**Issue by alexmireav** [sprinkler/rainmachine-web-ui#88]
It doesn't make sense to keep a Stop All button in the Programs page since only one program may run at any time.

Remove it, please

**Comment by nicupavel** [comment]
That's not entirely correct, stop all button clears entire water queue. In queue there can be multiple zones, which can come from multiple programs. For example I can run 2 programs manually, the zones will be scheduled with last program started on top of the other program zones. 
But the functionality is exactly the same with Stop all button from zones, it clears the watering queue.

**Comment by alexmireav** [comment]
@nicupavel I see. I neglected the thought of having a queue and it  makes sense. We shall revert, then

**Comment by alexmireav** [comment]
Thanks for reverting. Closing issue as invalid
